# **MINIPROJETO - ANÁLISE VAREJO**

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **1. ETAPA 1 — Leitura da base de dados - Carregando a base**

Nesta etapa será carregada a base de dados "base varejo.csv", objeto da análise.

In [7]:
#import kagglehub

# Download latest version
#path = kagglehub.dataset_download("namespaiva/base-varejo")

#print("Path to dataset files:", path)

In [8]:
import pandas as pd
path=r'/Base Varejo.csv';
df=pd.read_csv(path, sep=';', encoding='utf-8', engine='python');

df_original = df.copy()

display(df.head())

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

In [9]:
# Prints para análise geral do dataset apresentado

# Visualização das 5 primeiras linhas dos dados
print(f'AMOSTRAGEM 5 LINHAS:', '\n\n', df.head(5), '\n')

# Colunas
print(f'COLUNAS:', '\n\n', df.columns, '\n')

# Dimensões
print('DIMENSÕES:', df.shape, '\n')

# Tipos de dados
print(f'TIPOS DE DADOS:', '\n\n', df.info(), '\n')

# Valores nulos
print(f'VALORES NULOS:', '\n\n', df.isnull().sum(), '\n')

# Estatísticas
print(f'ESTATÍSTICAS:', '\n\n', df.describe(), '\n')

AMOSTRAGEM 5 LINHAS:

          DATA  CO_ID  CL_ID CL_GENERO  CL_EC  CL_FHL CL_SEG  PR_ID     PR_CAT  \
0  01/02/2019   1000    534         M      4       1      C     67    BEBIDAS
1  01/02/2019   1000    534         M      4       1      C     70    BEBIDAS
2  01/02/2019   1000    534         M      4       1      C    178    HIGIENE
3  01/02/2019   1000    534         M      4       1      C      4  ALIMENTOS
4  01/02/2019   1000    534         M      4       1      C    175    LIMPEZA

                PR_NOME
0  REFRIGERANTE GUARANA
1   REFRIGERANTE OUTROS
2       LENCO UMEDECIDO
3               ABACAXI
4     LIMPADOR MULTIUSO

COLUNAS:

 Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME'],
      dtype='object')

DIMENSÕES: (830000, 10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  object
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
dtypes: int64(5), object(5)
memory usage: 63.3+ MB
TIPOS DE DADOS:

 None

VALORES NULOS:

 DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

ESTATÍSTICAS:

                CO_ID          CL_ID          CL_EC        CL_FHL  \
count  830000.000000  830000.000000  830000.000000  830000.00000
mean   460045.089890     499.595204       2.596911       1.14654
std    265465.247541     287.568253       1.170599       1.41696
min      1000.000000       1.000000       1.000000       0.00000
25%    233117.000000     254.000000       2.000000       0.00000
50%    456517.000000     498.000000       3.000000       0.00000
75%    690132.000000     746.000000       4.000000       2.00000
max    919822.000000    1000.000000       5.000000       4.00000

               PR_ID
count  830000.000000
mean      115.051855
std        66.129241
min         1.000000
25%        58.000000
50%       115.000000
75%       172.000000
max       229.000000

### Constatações desta estapa 1:
Preliminarmente, após o carregamento da base de dados objeto no Colab, verificou-se que o arquivo carregado não possui divisão de colunas, ou seja, apenas linhas e uma única coluna de dados. Caso esteja visualizando via Colab, utilize o código do markdown abaixo e execute o código.
No mais, a base de dados apresentada possui 10 colunas e 830.000 linhas, cujos dados inseridos são do tipo str e int64. Segue legenda da denominação das colunas:
1. DATA: Data da compra;
2. CO_ID: Identificação do número de compra (número da nota fiscal);
3. CL_ID: Identificação do cliente (número do cliente);
4. CL_GENERO: Sexo biológico informado pelo cliente;
5. CL_EC: Estado civil do cliente: 1: Casado ou união estável; 2: Divorciado; 3: Separado; 4. Solteiro; 5: Viúvo.
6. CL_FHL: Número de filhos do cliente;
7. CL_SEG: Segmentação econômica do cliente (classe A, B ou C);
8. PR_ID: Código do produto (SKU) adquirido;
9. PR_CAT: Categoria do produto adquirido;
10. PR_NOME: Nome do produto adquirido.

#Carrega a base especificando o separador ponto e vírgula
df = pd.read_csv("Base Varejo.csv", sep=";")
#Remove colunas totalmente vazias ou sem nome (geradas pelos ';' extras ao final)
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
#Atualiza a cópia da base original
df_original = df.copy()
#Exibe as informações e as primeiras linhas do DataFrame correto
print("Nova quantidade de colunas:", df.shape[1])
print("Colunas:", df.columns.tolist())
#Tipos e quantidade de valores preenchidos
df.info()
display(df.head())

## **2. ETAPA 2 — Diagnóstico da base de dados - Estrutura da base**

### **2.1. Investigação de estrutura e tipos**

In [10]:
# Quantidade de linhas e colunas
print("Quantidade de linhas: ", df.shape[0])
print("quantidade de colunas: ", df.shape[1])

Quantidade de linhas:  830000
quantidade de colunas:  10

In [11]:
# Nomes das colunas
print(df.columns.tolist())

['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']

In [12]:
# Tipos e quantidade de valores preenchidos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  object
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
dtypes: int64(5), object(5)
memory usage: 63.3+ MB

### **2.2. Investigação de valores ausentes**

In [13]:
# Conferência preliminar - valores ausentes existem por coluna
print("Ausência por coluna: ")
display(df.isna().sum())

print(
    "Duplicadas completas excedentes: ",
    df.duplicated().sum()
)

Ausência por coluna:

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

Duplicadas completas excedentes:  96553

### **2.3. Investigação de textos vazios e preenchidos apenas com espaços**

In [14]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  object
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
dtypes: int64(5), object(5)
memory usage: 63.3+ MB

None

In [15]:
# verificar os espaços

colunas_texto = [
    'CL_GENERO',
    'CL_SEG',
    'PR_CAT',
    'PR_NOME',
    ]

for coluna in colunas_texto:
    quantidade_em_branco = (
        df[coluna]
        .astype("string")
        .str.strip()
        .eq("")
        .sum()
    )

print(coluna, ":", quantidade_em_branco)

PR_NOME : 0

In [16]:
colunas_alvo = ['CL_GENERO', 'CL_SEG', 'PR_CAT', 'PR_NOME']

# Verifica para cada linha se alguma das colunas selecionadas está vazia ou contém apenas espaços
clientes_em_branco = (
    df[colunas_alvo]
    .astype("string")
    .apply(lambda x: x.str.strip() == "")
    .any(axis=1)
)

print(
    "Clientes preenchidos apenas com espaços em alguma das colunas: ",
    clientes_em_branco.sum()
)

display(
    df.loc[
        clientes_em_branco,
        colunas_alvo
    ]
)

Clientes preenchidos apenas com espaços em alguma das colunas:  0

Empty DataFrame
Columns: [CL_GENERO, CL_SEG, PR_CAT, PR_NOME]
Index: []

### **2.4. Investigação de duplicidades e distinção de linhas**

In [17]:
print(
    "Repetições completas além da primeira ocorrência: ",
    df.duplicated().sum() # marca as repetições da primeira ocorrência
)

print(
    "Linhas que participam de grupos repetidos: ",
    df.duplicated(keep=False).sum() # marca todas as ocorrências dos registros repetidos
)

print(
    "Identificadores de pedidos distintos: ",
    df["CO_ID"].nunique()
)

Repetições completas além da primeira ocorrência:  96553
Linhas que participam de grupos repetidos:  184330
Identificadores de pedidos distintos:  18471

In [18]:
# Visualize as linhas duplicadas
display(
    df.loc[df.duplicated(keep=False)]
)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ

### **2.5. Inconsistências de texto**

In [19]:
display(
    df['DATA'].value_counts(dropna=False)
)

DATA
21/08/2020    4641
15/04/2019    4628
23/10/2021    4569
22/01/2022    4539
31/01/2022    4539
              ...
19/01/2019     471
31/10/2019     468
31/10/2021     445
07/12/2021     433
30/04/2022     403
Name: count, Length: 333, dtype: int64

In [20]:
display(
    df["CO_ID"].value_counts(dropna=False)
)

CO_ID
919626    89
2224      89
100465    89
917050    89
699110    89
          ..
773568     1
914348     1
312660     1
58928      1
915285     1
Name: count, Length: 18471, dtype: int64

In [21]:
display(
    df["CL_ID"].value_counts(dropna=False)
)

CL_ID
822    1777
485    1647
369    1531
397    1509
971    1497
       ...
515     350
489     330
20      327
716     324
490     300
Name: count, Length: 1000, dtype: int64

In [22]:
display(
    df["CL_GENERO"].value_counts(dropna=False)
)

CL_GENERO
F    432576
M    397424
Name: count, dtype: int64

In [23]:
display(
    df["CL_EC"].value_counts(dropna=False)
)

CL_EC
3    213742
4    202618
2    194990
1    194873
5     23777
Name: count, dtype: int64

In [24]:
display(
    df["CL_FHL"].value_counts(dropna=False)
)

CL_FHL
0    435501
2    106622
3    104685
1    102813
4     80379
Name: count, dtype: int64

In [25]:
display(
    df["CL_SEG"].value_counts(dropna=False)
)

CL_SEG
B    530163
C    232101
A     67736
Name: count, dtype: int64

In [26]:
display(
    df["PR_ID"].value_counts(dropna=False)
)

PR_ID
93     3773
98     3760
37     3757
61     3746
129    3744
       ...
117    3521
197    3520
41     3515
21     3510
26     3471
Name: count, Length: 229, dtype: int64

In [27]:
display(
    df["PR_CAT"].value_counts(dropna=False)
)

PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64

In [28]:
display(
    df["PR_NOME"].value_counts(dropna=False)
)

PR_NOME
PRESUNTO COZIDO          14381
SARDINHA                  7490
GEL                       7399
BANANA                    7385
DESENGORDURANTE           7378
                         ...
#N/D                      3650
ABSORVENTE                3639
ALCOOL                    3611
ALIMENTO PARA PASSARO     3605
ALHO                      3574
Name: count, Length: 118, dtype: int64

### Constatações da do item 2. ETAPA 2 — Diagnóstico da base de dados - Estrutura da base:
Verificou-se a inexistência de registros contendo campos vazios ou preenchidos exclusivamente por espaços em branco. Em relação à identificação de possíveis lançamentos em duplicidade, constatou-se que, embora haja repetição de informações em determinadas colunas, os produtos adquiridos são distintos. Dessa forma, tais registros não caracterizam duplicidade de lançamento, uma vez que foram identificadas evidências de que os produtos foram adquiridos pelo mesmo cliente, na mesma data, por meio de uma única operação de compra, conforme demonstrado pela emissão da mesma nota fiscal.
Com relação ao item "2.5. Inconsistências de texto", evidenciou-se que:
- a coluna **DATA** está definida como ***int64***. Neste caso a ação adotada será de transformar no tipo ***date***.
- a coluna **CL_EC** está definida como ***int64***. Neste caso a ação adotada será de transformar no tipo ***str***, ou ainda, alterar a respectiva numeração pelo significado (1: Casado ou união estável; 2: Divorciado; 3: Separado; 4. Solteiro; 5: Viúvo.).
- a coluna **PR_CAT** possui categoria de denominação **#N/D**. Neste caso, será adotada para ND.

1. DATA: Data da compra;
2. CO_ID: Identificação do número de compra (número da nota fiscal);
3. CL_ID: Identificação do cliente (número do cliente);
4. CL_GENERO: Sexo biológico informado pelo cliente;
5. CL_EC: Estado civil do cliente: 1: Casado ou união estável; 2: Divorciado; 3: Separado; 4. Solteiro; 5: Viúvo.
6. CL_FHL: Número de filhos do cliente;
7. CL_SEG: Segmentação econômica do cliente (classe A, B ou C);
8. PR_ID: Código do produto (SKU) adquirido;
9. PR_CAT: Categoria do produto adquirido;
10. PR_NOME: Nome do produto adquirido.

## 3. Etapa 3 - Limpeza

In [29]:
# Converter de int64 para date
df['DATA'] = pd.to_datetime(
    df['DATA'],
    format='%d/%m/%Y'
).dt.date

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  object
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
dtypes: int64(5), object(5)
memory usage: 63.3+ MB

In [31]:
# Mapeamento dos códigos do Estado Civil para seus significados descritivos
mapeamento_ec = {
    1: 'Casado ou união estável',
    2: 'Divorciado',
    3: 'Separado',
    4: 'Solteiro',
    5: 'Viúvo'
}

# Substitui os valores numéricos pelas strings correspondentes
df['CL_EC'] = df['CL_EC'].map(mapeamento_ec).astype(str)

# Exibe a distribuição dos novos valores e as primeiras linhas do DataFrame
print("Distribuição do Estado Civil:")
print(df['CL_EC'].value_counts())
print("\nTipos de dados atualizados:")
print(df[['CL_EC']].info())

display(df.head())

Distribuição do Estado Civil:
CL_EC
Separado                   213742
Solteiro                   202618
Divorciado                 194990
Casado ou união estável    194873
Viúvo                       23777
Name: count, dtype: int64

Tipos de dados atualizados:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   CL_EC   830000 non-null  object
dtypes: object(1)
memory usage: 6.3+ MB
None

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,2019-02-01,1000,534,M,Solteiro,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,2019-02-01,1000,534,M,Solteiro,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,2019-02-01,1000,534,M,Solteiro,1,C,178,HIGIENE,LENCO UMEDECIDO
3,2019-02-01,1000,534,M,Solteiro,1,C,4,ALIMENTOS,ABACAXI
4,2019-02-01,1000,534,M,Solteiro,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

In [36]:
# Substitui a denominação '#N/D' na coluna PR_CAT por 'ND'
df['PR_CAT'] = df['PR_CAT'].replace('#N/D', 'ND')

# Exibe a contagem de valores na coluna para validar a alteração
print("Valores atualizados na coluna PR_CAT:")
print(df['PR_CAT'].value_counts(dropna=False))

Valores atualizados na coluna PR_CAT:
PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
ND              3650
Name: count, dtype: int64

## 4. Etapa 4 - Funções

In [38]:
def obter_top3_coluna(dataframe, coluna):
    """
    Retorna os top 3 valores mais frequentes de uma coluna,
    suas contagens e a representatividade percentual.
    """
    contagem = dataframe[coluna].value_counts()
    percentual = dataframe[coluna].value_counts(normalize=True) * 100

    top3 = pd.DataFrame({
        'Valor': contagem.index[:3],
        'Frequência': contagem.values[:3],
        'Percentual (%)': percentual.values[:3].round(2)
    })
    return top3

# Gerar o top 3 para cada uma das colunas do DataFrame
for col in df.columns:
    print("="*50)
    print(f"TOP 3 DA COLUNA: {col}")
    print("="*50)
    display(obter_top3_coluna(df, col))
    print("\n")

==================================================
TOP 3 DA COLUNA: DATA
==================================================

        Valor  Frequência  Percentual (%)
0  2020-08-21        4641            0.56
1  2019-04-15        4628            0.56
2  2021-10-23        4569            0.55

==================================================
TOP 3 DA COLUNA: CO_ID
==================================================

    Valor  Frequência  Percentual (%)
0  919626          89            0.01
1    2224          89            0.01
2  100465          89            0.01

==================================================
TOP 3 DA COLUNA: CL_ID
==================================================

   Valor  Frequência  Percentual (%)
0    822        1777            0.21
1    485        1647            0.20
2    369        1531            0.18

==================================================
TOP 3 DA COLUNA: CL_GENERO
==================================================

  Valor  Frequência  Percentual (%)
0     F      432576           52.12
1     M      397424           47.88

==================================================
TOP 3 DA COLUNA: CL_EC
==================================================

        Valor  Frequência  Percentual (%)
0    Separado      213742           25.75
1    Solteiro      202618           24.41
2  Divorciado      194990           23.49

==================================================
TOP 3 DA COLUNA: CL_FHL
==================================================

   Valor  Frequência  Percentual (%)
0      0      435501           52.47
1      2      106622           12.85
2      3      104685           12.61

==================================================
TOP 3 DA COLUNA: CL_SEG
==================================================

  Valor  Frequência  Percentual (%)
0     B      530163           63.88
1     C      232101           27.96
2     A       67736            8.16

==================================================
TOP 3 DA COLUNA: PR_ID
==================================================

   Valor  Frequência  Percentual (%)
0     93        3773            0.45
1     98        3760            0.45
2     37        3757            0.45

==================================================
TOP 3 DA COLUNA: PR_CAT
==================================================

       Valor  Frequência  Percentual (%)
0  ALIMENTOS      434767           52.38
1    HIGIENE      155574           18.74
2    LIMPEZA      145754           17.56

==================================================
TOP 3 DA COLUNA: PR_NOME
==================================================

             Valor  Frequência  Percentual (%)
0  PRESUNTO COZIDO       14381            1.73
1         SARDINHA        7490            0.90
2              GEL        7399            0.89

In [42]:
def obter_bottom3_coluna(dataframe, coluna):
    """
    Retorna os 3 valores menos frequentes (inverso do top 3) de uma coluna,
    suas contagens e a representatividade percentual.
    """
    # Ordenamos de forma crescente (do menos frequente para o mais frequente)
    contagem = dataframe[coluna].value_counts(ascending=True)
    percentual = dataframe[coluna].value_counts(ascending=True, normalize=True) * 100

    bottom3 = pd.DataFrame({
        'Valor': contagem.index[:3],
        'Frequência': contagem.values[:3],
        'Percentual (%)': percentual.values[:3].round(4)
    })
    return bottom3

# Gerar o bottom 3 (valores menos comuns) para cada uma das colunas do DataFrame
for col in df.columns:
    print("="*50)
    print(f"TOP 3 MENOS COMUM DA COLUNA: {col}")
    print("="*50)
    display(obter_bottom3_coluna(df, col))
    print("\n")

==================================================
TOP 3 MENOS COMUM DA COLUNA: DATA
==================================================

        Valor  Frequência  Percentual (%)
0  2022-04-30         403          0.0486
1  2021-12-07         433          0.0522
2  2021-10-31         445          0.0536

==================================================
TOP 3 MENOS COMUM DA COLUNA: CO_ID
==================================================

    Valor  Frequência  Percentual (%)
0    1985           1          0.0001
1  571291           1          0.0001
2  107666           1          0.0001

==================================================
TOP 3 MENOS COMUM DA COLUNA: CL_ID
==================================================

   Valor  Frequência  Percentual (%)
0    490         300          0.0361
1    716         324          0.0390
2     20         327          0.0394

==================================================
TOP 3 MENOS COMUM DA COLUNA: CL_GENERO
==================================================

  Valor  Frequência  Percentual (%)
0     M      397424         47.8824
1     F      432576         52.1176

==================================================
TOP 3 MENOS COMUM DA COLUNA: CL_EC
==================================================

                     Valor  Frequência  Percentual (%)
0                    Viúvo       23777          2.8647
1  Casado ou união estável      194873         23.4787
2               Divorciado      194990         23.4928

==================================================
TOP 3 MENOS COMUM DA COLUNA: CL_FHL
==================================================

   Valor  Frequência  Percentual (%)
0      4       80379          9.6842
1      1      102813         12.3871
2      3      104685         12.6127

==================================================
TOP 3 MENOS COMUM DA COLUNA: CL_SEG
==================================================

  Valor  Frequência  Percentual (%)
0     A       67736          8.1610
1     C      232101         27.9640
2     B      530163         63.8751

==================================================
TOP 3 MENOS COMUM DA COLUNA: PR_ID
==================================================

   Valor  Frequência  Percentual (%)
0     26        3471          0.4182
1     21        3510          0.4229
2     41        3515          0.4235

==================================================
TOP 3 MENOS COMUM DA COLUNA: PR_CAT
==================================================

        Valor  Frequência  Percentual (%)
0          ND        3650          0.4398
1  ACESSORIOS       14557          1.7539
2         PET       32399          3.9035

==================================================
TOP 3 MENOS COMUM DA COLUNA: PR_NOME
==================================================

                   Valor  Frequência  Percentual (%)
0                   ALHO        3574          0.4306
1  ALIMENTO PARA PASSARO        3605          0.4343
2                 ALCOOL        3611          0.4351

In [43]:
# Seleção da coluna numérica analítica: 'CL_FHL' (Número de Filhos dos clientes)
# Identificadores como CO_ID, CL_ID e PR_ID foram desconsiderados por serem apenas códigos de identificação.

estatisticas_filhos = df['CL_FHL'].describe()

print("ESTATÍSTICAS BÁSICAS — COLUNA: CL_FHL (Número de Filhos)")
print("="*60)
print(f"Contagem de valores válidos: {estatisticas_filhos['count']:,.0f}")
print(f"Média de filhos por cliente: {estatisticas_filhos['mean']:.4f}")
print(f"Mínimo:                       {estatisticas_filhos['min']:.0f}")
print(f"Máximo:                       {estatisticas_filhos['max']:.0f}")
print(f"Desvio Padrão:               {estatisticas_filhos['std']:.4f}")
print("="*60)

# Explicação dos resultados requerida:
print("\n--- ANÁLISE E EXPLICAÇÃO DOS RESULTADOS ---")
print("1. Unidade Analisada: A unidade de medida desta análise é o 'número de filhos' por registro de cliente no varejo.")
print("2. Média (~1.15 filhos): Em média, os clientes da base possuem aproximadamente 1,15 filhos.")
print("3. Mínimo (0) e Máximo (4): A amplitude varia de clientes sem nenhum filho (0) até o limite máximo registrado de 4 filhos.")

ESTATÍSTICAS BÁSICAS — COLUNA: CL_FHL (Número de Filhos)
============================================================
Contagem de valores válidos: 830,000
Média de filhos por cliente: 1.1465
Mínimo:                       0
Máximo:                       4
Desvio Padrão:               1.4170
============================================================

--- ANÁLISE E EXPLICAÇÃO DOS RESULTADOS ---
1. Unidade Analisada: A unidade de medida desta análise é o 'número de filhos' por registro de cliente no varejo.
2. Média (~1.15 filhos): Em média, os clientes da base possuem aproximadamente 1,15 filhos.
3. Mínimo (0) e Máximo (4): A amplitude varia de clientes sem nenhum filho (0) até o limite máximo registrado de 4 filhos.

## 5. Análise

In [45]:
# =====================================================================
# ETAPA 5 — FILTROS E AGRUPAMENTOS (ESTRITAMENTE CÓDIGO)
# =====================================================================
import pandas as pd

# Aplicando o filtro focado nos clientes do segmento socioeconômico 'A'
df_classe_a = df[df['CL_SEG'] == 'A']

# Resumo 1: Contagem absoluta de registros (itens individuais vendidos) por categoria
resumo_categoria = df_classe_a.groupby('PR_CAT').size().reset_index(name='Total_Itens_Vendidos')
resumo_categoria = resumo_categoria.sort_values(by='Total_Itens_Vendidos', ascending=False)

# Resumo 2: Compras únicas (Notas Fiscais) e Clientes únicos por Gênero
resumo_genero = df_classe_a.groupby('CL_GENERO').agg(
    Clientes_Unicos=('CL_ID', 'nunique'),
    Compras_Unicas=('CO_ID', 'nunique'),
    Itens_Totais=('CO_ID', 'count')
).reset_index()

# Exibição dos resultados estruturados na tela
print("=== RESUMO 1: Contagem de Registros por Categoria (Segmento A) ===")
display(resumo_categoria)

print("\n=== RESUMO 2: Compras Únicas (Notas) e Clientes Únicos por Gênero (Segmento A) ===")
display(resumo_genero)

=== RESUMO 1: Contagem de Registros por Categoria (Segmento A) ===

       PR_CAT  Total_Itens_Vendidos
1   ALIMENTOS                 35292
3     HIGIENE                 12844
4     LIMPEZA                 11915
2     BEBIDAS                  3601
6         PET                  2620
0  ACESSORIOS                  1175
5          ND                   289

=== RESUMO 2: Compras Únicas (Notas) e Clientes Únicos por Gênero (Segmento A) ===

  CL_GENERO  Clientes_Unicos  Compras_Unicas  Itens_Totais
0         F               40             700         32875
1         M               44             792         34861

# **Relatório de Análise Geral do Dataset e Conclusão**

Este relatório apresenta o diagnóstico completo do comportamento de compras a partir do processamento e limpeza efetuados na base de dados de varejo.

---

## **1. Dimensão e Estrutura dos Dados**

* **Volume Geral:** O banco de dados registra **830.000 linhas** (itens adicionados ao carrinho).
* **Transações vs. Clientes:** Foram contabilizadas **18.471 compras únicas** (notas fiscais/cupons emitidos), divididas entre **1.000 clientes únicos** cadastrados.
* **Comportamento de Cesta:** O mesmo cliente retorna recorrentemente para realizar compras no estabelecimento (média de ~18,5 compras por cliente). Além disso, cada cupom fiscal de compra carrega, em média, **44,9 itens**, indicando um perfil forte de "compras de abastecimento/mês".

---

## **2. Perfil Comportamental e Demográfico do Consumidor**

* **Gênero:** Há um equilíbrio quase perfeito na base de clientes. No recorte efetuado para a **Classe A** (Segmento A), por exemplo, identificou-se **40 clientes mulheres** (gerando 700 notas fiscais) e **44 clientes homens** (gerando 792 notas fiscais).
* **Estado Civil:** Os clientes estão distribuídos de forma muito equilibrada entre as categorias civis. Solteiros, Casados, Divorciados e Separados mantêm um patamar similar de cerca de ~190k a ~210k registros cada, enquanto os viúvos representam a menor fatia com ~23k registros.
* **Núcleo Familiar (Filhos):** O número médio de filhos por cliente é de **1,15**, variando entre 0 e 4 filhos. A mediana é 0, o que nos diz que a maioria dos clientes registrados não possui filhos.

---

## **3. Mix de Produtos e Preferências**

* **Domínio de Alimentos:** A categoria **Alimentos** é a líder absoluta com **434.767 registros** (mais de 50% de todo o volume operado na base).
* **Outras Categorias:** Higiene (~155k) e Limpeza (~145k) aparecem como as principais categorias secundárias. Bebidas, Pet e Acessórios completam a cauda longa de vendas.
* **Saneamento Efetuado:** Identificou-se e removeu-se a inconsistência de texto `#N/D` na coluna de categorias (`PR_CAT`), normalizando 3.650 registros para a sigla limpa `ND`.

---

## **Conclusão Estratégica**

A base de dados de varejo analisada possui excelente consistência e qualidade (zero nulos estruturais). O perfil de consumo é amplamente dominado por produtos essenciais (Alimentos), servindo a um público de classe média/popular que realiza compras volumosas de reposição periódica.

A alta fidelidade dos clientes (1.000 clientes gerando 18 mil cupons de compra com média de ~45 itens por transação) indica que o estabelecimento é o canal principal de abastecimento dessas famílias.

**Recomendação:** Campanhas promocionais e posicionamento de gôndolas devem focar em estratégias de *cross-selling* (venda cruzada), estimulando que o cliente de Alimentos preencha seu carrinho volumoso também com os produtos de Higiene e Limpeza, que são as outras categorias de maior relevância na operação.

## 6. Exportação

In [46]:
from google.colab import files

# Caminho onde queremos salvar o arquivo temporariamente no Colab
nome_arquivo = 'base_varejo_limpa.csv'

# Exporta o DataFrame limpo 'df' para CSV usando ponto e vírgula como separador
df.to_csv(nome_arquivo, index=False, sep=';', encoding='utf-8')

# Dispara o download automático do arquivo para a sua máquina local
files.download(nome_arquivo)